apiVersion: v2
name: maplarge
description: MapLarge Kubernetes Helm Chart
kubeVersion: ">= 1.19.0-0"
type: application
version: 3.4.1
appVersion: "maplarge"
maintainers:
  - name: MapLarge DevOps
    email: maplarge.devops@maplarge.com
